{% set name = "idaes-pse" %}
{% set version = "2.6.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/IDAES/{{ name }}/archive/{{ version }}.tar.gz
  sha256: dcc09ff01b30d5fc60cf0b4fc68b41b0c763ea8b6ae78237f5d4da3f563bb334

build:
  noarch: python
  number: 0
  entry_points:
    - idaes = idaes.commands.base:command_base
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-cache-dir --ignore-installed"

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - click >=8
    - matplotlib-base
    - networkx
    - numpy >=1.17
    - pandas
    - pint
    - pip
    - pyomo >=6.8.0
    - pytest
    - pyyaml
    - scipy
    - sympy

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - idaes
    - idaes.core
    - idaes.core.base
  commands:
    - pip check
    - idaes --version
    - idaes --help

about:
  home: "https://idaes.org"
  license: BSD-3-Clause-LBNL
  license_family: BSD
  license_file: LICENSE.md 
  summary: "IDAES Process Systems Engineering Framework"
  doc_url: "https://idaes-pse.readthedocs.io"
  dev_url: "https://github.com/IDAES/idaes-pse"

extra:
  recipe-maintainers:
    - lbianchi-lbl
